# Generated by Django 4.1.5 on 2023-03-06 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('current_address', models.TextField()),
                ('birth_year', models.IntegerField()),
                ('skill_level', models.IntegerField()),
                ('preferred_working_location', models.TextField(null=True)),
                ('working_status', models.CharField(max_length=100, null=True)),
                ('employee_phone', models.IntegerField()),
                ('employee_gender', models.CharField(max_length=10)),
                ('national_id', models.CharField(max_length=100)),
                ('national_id_issue_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('source_reference_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_type', models.CharField(max_length=100)),
                ('physical_condition', models.CharField(max_length=100)),
                ('memory_condition', models.CharField(max_length=100)),
                ('ulcer', models.BooleanField()),
                ('neural_disease', models.BooleanField()),
                ('endo_tube', models.BooleanField()),
                ('nebuliser', models.BooleanField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('service_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('shift_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('customer_id', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('shift_status', models.CharField(max_length=100)),
                ('caring_address', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('customer_requirements', models.CharField(max_length=100)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caregiver')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patients')),
            ],
        ),
    ]
