# Generated by Django 4.1.5 on 2023-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_caregiver_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='national_id_issue_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
